// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDRX_h0p2C04qdERC4IJRTj-cP3h8bP-X4',
    appId: '1:17551309484:android:3efb56aa3c3bbfb9fe3d09',
    messagingSenderId: '17551309484',
    projectId: 'surfs-up-3437e',
    storageBucket: 'surfs-up-3437e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDUnrmLHFuFm9_Ym2yryMIVAEvjDzcWTFc',
    appId: '1:17551309484:ios:4ec8e71fcd3efc81fe3d09',
    messagingSenderId: '17551309484',
    projectId: 'surfs-up-3437e',
    storageBucket: 'surfs-up-3437e.appspot.com',
    androidClientId: '17551309484-11uaasmdi8ts7hjn0avfrb56jq5pfbk2.apps.googleusercontent.com',
    iosClientId: '17551309484-u1mi503bn8ug167p27srvieabb1e5uso.apps.googleusercontent.com',
    iosBundleId: 'com.project.surfs-up',
  );
}
